-- drop procedures
DROP PROCEDURE IF EXISTS v3_create_file_record;

-- drop tables
DROP TABLE IF EXISTS v3_bugs_comments;
DROP TABLE IF EXISTS v3_bugs;
DROP TABLE IF EXISTS v3_votes;
DROP TABLE IF EXISTS v3_arenas_revs;
DROP TABLE IF EXISTS v3_tracks_revs;
DROP TABLE IF EXISTS v3_karts_revs;
DROP TABLE IF EXISTS v3_cache;
DROP TABLE IF EXISTS v3_files;
DROP TABLE IF EXISTS v3_addons;

DROP TABLE IF EXISTS v3_server_conn;
DROP TABLE IF EXISTS v3_servers;
DROP TABLE IF EXISTS v3_host_votes;
DROP TABLE IF EXISTS v3_client_sessions;
DROP TABLE IF EXISTS v3_news;
DROP TABLE IF EXISTS v3_logs;
DROP TABLE IF EXISTS v3_notifications;
DROP TABLE IF EXISTS v3_friends;
DROP TABLE IF EXISTS v3_achieved;
DROP TABLE IF EXISTS v3_achievements;
DROP TABLE IF EXISTS v3_verification;
DROP TABLE IF EXISTS v3_users;
DROP TABLE IF EXISTS v3_role_permissions;
DROP TABLE IF EXISTS v3_roles;

DROP TABLE IF EXISTS v3_stats;
DROP TABLE IF EXISTS v3_config;
DROP TABLE IF EXISTS v3_music;
DROP TABLE IF EXISTS v3_clients;

